### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by QuentinRoy** [QuentinRoy/tie#8]
Current build is broken:
```
ERROR in ./lib/constraint.js
Module build failed: TypeError: /Users/quentinroy/Workspace/tie/lib/constraint.js: Cannot set property 'Symbol(should not be considered a local binding)' of undefined
    at Object.push (/Users/quentinroy/Workspace/tie/node_modules/babel-helper-define-map/lib/index.js:96:37)
    at pushToMap (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:191:25)
    at pushMethod (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:531:10)
    at pushBody (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:312:16)
    at buildBody (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:244:10)
    at run (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:151:10)
    at PluginPass.ClassExpression (/Users/quentinroy/Workspace/tie/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:63:60)
    at newFn (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:159:21)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:159:21)
    at TraversalContext.visitMultiple (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/quentinroy/Workspace/tie/node_modules/babel-traverse/lib/index.js:139:17)
 @ ./lib/es-index.js 14:18-41
```

I does not seem to be caused by tie though as previously working version are not working anymore. This is probably due to babel though it is not fixed by installing the exact `package.json` version.

**Comment by QuentinRoy** [comment]
The cause has been identified. Last Babel version breaks when a class method has the name of a JS global function (e.g. `isNaN`, `parseInt` or `parseFloat`, see [babel task T7010](https://phabricator.babeljs.io/T7010)). As a result, corresponding constraint's modifier are not working.
